{% set version = "1.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microseq
  version: {{ version|replace("-", "_") }}

source:
  fn: microseq_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/microseq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/microseq/microseq_{{ version }}.tar.gz
  sha256: 36f254cb9fb7db0a6f79fc5c5089975fd0ea1b948cff17ea07f6f7ea457f73eb

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.0

test:
  commands:
    - $R -e "library('microseq')"           # [not win]
    - "\"%R%\" -e \"library('microseq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=microseq
  license: GPL-2
  summary: Basic functions for microbial sequence data analysis. The idea is to use the basic
    R data structures as much as possible, without building complex data types.
  license_family: GPL2

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
