{% set version = "2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microseq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/microseq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/microseq/microseq_{{ version }}.tar.gz
  sha256: 998754a045f1b334b5e4b23ac2de215507d96219b7b1f5c89fdf0d56f6e19dc4

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.0
    - r-stringr
    - r-tibble
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.0
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('microseq')"           # [not win]
    - "\"%R%\" -e \"library('microseq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=microseq
  license: GPL-2
  summary: Basic functions for microbial sequence data analysis. The idea is to use the basic
    R data structures as much as possible, without building complex data types.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: microseq
# Type: Package
# Title: Basic Biological Sequence Handling
# Version: 1.3
# Date: 2019-10-26
# Author: Lars Snipen, Kristian Hovde Liland
# Maintainer: Lars Snipen <lars.snipen@nmbu.no>
# Description: Basic functions for microbial sequence data analysis. The idea is to use the basic R data structures as much as possible, without building complex data types.
# License: GPL-2
# Depends: R (>= 3.5.0), tibble, stringr
# Imports: Rcpp (>= 0.12.0)
# LinkingTo: Rcpp (>= 0.12.0)
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-10-27 11:47:58 UTC; larssn
# Repository: CRAN
# Date/Publication: 2019-10-27 12:20:02 UTC
