travis:
  secure:
    BINSTAR_TOKEN: QJ2gJXdiHO3DDYsHOIGPACE2m2ZS+ztVnRH3s5JbvoCxo2R2SQLVWzbSJIl8wcwKtpY2Fe6OZjkr2BFimlFbI30RkBfGUEGacQPLBC5qorGrCKuOF+xr89tbUvunN98M5A+n2KVSi8AYFlu0OBfnrURRolJv+ioP3NtM5uBmVZkYt3kJubVB8LB6OL832MxKLtR5hC+d3eqlQnmJ8131miDa1izoMapgGACMhmFnMPD3Nj/5WBbCUhrl0bGWXWj5Dp4zLBdiEuey6GlzZRCeWhYN/sU/xlAskxg1xDZE/EhsU1JtUC0eGZMjI61u2GXgeLe1zNypcwFt9rB/0OFCthZkJzJf2fAiM0koypwy6pS/hszSEWwG0lH2kaUTADupRSiiqwu3S7asD4608lqWzId7/n0GrC+mnl+3bQgEqDhjDLG6xNPTNi7fhmAKDhLiagO7ilBAHsiiHWDN4fBq64DGuuH1IwDZefLyuE5dsVcocs5P7j+vH0CE6ZB1l6FBkB+qzYV1Pi7llenSWf8IdwbE1b1JmMgd/SrdLrYvEDPTF85VnMh2f6TfGbYeqm2qtXnt5411A7ytq5WUa5CX8iyFpq+3mphcvYQckPMF9j8m5VhrwgjLn3mqchuwiKskeha6ZrFpqa5cX5skFM40lmTOMCM/zvzcvrS5+G/tlz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
