travis:
  secure:
    BINSTAR_TOKEN: GhFz1fbiKFTaHGNLtTMtJ8M2NdTCi9S/ow5XTae0chwrUxbUxDFHXUdzP3mRphj4b/+n3V4Ea0YKsej2e3lt0rtJevQTtHBG3I+5qMT8gj4B/WjxwleXHVb06TeuuMvyi8xu9QtCehEHSv9EfzrEOMNTK2dSh0rXWegrgwLpCh2wmZbosw58w6/e4nBnj5w9/y7QYWQCUmsLvxX2rjsbXSKHV/hqGpTp7Q4T+KxvtFu9zKJ64ltGEtvj0FlxvEMcGxK302uSRRkkXdb27pspEFBG+G41wZQvcDrEYyO8zGqUoAvkTBzPz5/82JjWGVJ073Z2EbRNSAgkkaoKnr56NZPsTuHLVlYC459NCCd0PQxGPVS3OLuaQdoZsvY4YqLCQxl3rEhGwOm+KPF2cRk6jWmSPajixZi69zXvWy+6b8WLXCRZB5rHqj9INYFpT9BwpGcynSeJrZiUCgqcvDlEPFJ5xenatziGV6jQomssN0278knYInSjfv0PH2SvFq+i/Ndx+pZNFFW2H9ounOYLCmC/PV3Ux0CpgmxBqsu7Fx+yCVuZmRwfJPyQsFwjMMol8OChF1+hKOOxL3onE4LKm3sgjgbCvOdtGGXpqTfYMjTpVG5OkUIrnamjtjK3ma4J0AJuPbyNvPL1mGX4g6ZRol5ebjqxVCGUPEVcUhocPYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
